<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3c2d240a-0ea5-42bb-9d00-7f9f62e7c3bf</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RootNamespace>SURIMI_controller</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BSR.Surimi.Surimi-Protocol.Grpc.Csharp" Version="1.83.10103.89+0ef92bb4a1bf" />
    <PackageReference Include="Eii.BlobStore" Version="2.0.*" />
    <PackageReference Include="Eii.BlobStore.S3" Version="1.0.*" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.83.0" />
    <PackageReference Include="Grpc.StatusProto" Version="2.80.0" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
    <PackageReference Include="SURIMI.Common" Version="1.0.*" />
    <PackageReference Include="SURIMI.Datamodel" Version="3.0.*" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Includes\aegean_sea\aegean_sea_contract.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Includes\anchovy_bay\anchovy_bay_contract.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Includes\northwestern_med\northwestern_med_contract.yaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
    
  <PropertyGroup>
    <NoWarn>$(NoWarn);EXTEXP0001</NoWarn>
  </PropertyGroup>
    
</Project>
